### ISSUE TITLE
Add kitty support

### ISSUE THREAD

**Issue by paolosezart** [WinSSHTerm/WinSSHTerm#14]
I have a request to the developer to add a fork of PuTTY called kitty.
https://www.9bis.net/kitty/#!pages/download.md

**Comment by WinSSHTerm** [comment]
KiTTY is based on the code base of PuTTY 0.76, which contains several security issues. I recommend to use the latest version of PuTTY

**Comment by paolosezart** [comment]
Then at least the ability to import sessions from KiTTY. I have quite a lot of servers in KiTTY (about 200) and it is very long and inconvenient to transfer one by one.
Thanks!

**Comment by WinSSHTerm** [comment]
There is a migration tool available here https://github.com/P-St/Migrate2WinSSHTerm
