### ISSUE TITLE
ssh window disappears when using touchpad

### ISSUE THREAD

**Issue by caoguosong** [WinSSHTerm/WinSSHTerm#15]
The ssh window usually disappears or is moved from the frame when I use the touchpad .

There were common issues in previous versions.

![image](https://github.com/WinSSHTerm/WinSSHTerm/assets/67968014/fd1a69d6-a0d7-4a66-b44a-060561ed52c8)

**Comment by WinSSHTerm** [comment]
Thanks for your feedback. Could you please send the content of Help->Info here or send it via email to "pst.freeware _at_ gmail.com"?
This behaviour could be caused by some other software. E.g. the "Lenovo Auto Scroll Utility", which shows up as "virtscrl.exe" in the task manager, has caused issues in the past. You can try disabling this kind of software/tools and see if it helps

**Comment by caoguosong** [comment]
Thanks!

The problem is solved when the software  "Lenovo Auto Scroll Utility" has been uninstalled.

the content of Help->Info is:

Windows Info
============
Version:    Windows 10 Pro, Release 2009, Display Version 22H2
Build:      19045.4170 (x86, 64-bit)

Version Info
============
WinSSHTerm: 2.33.2 (x86, 64-bit)
PuTTY:      0.79 (x86, 64-bit)
Plink:      0.79 (x86, 64-bit)
Pageant:    0.79 (x86, 64-bit)
WinSCP:     6.1.2 (x86, 32-bit)
VcXsrv:     1.17.2.0 (x86, 64-bit)

Path Info
=========
WinSSHTerm: E:\tools\ssh\winsshterm\WinSSHTerm\WinSSHTerm.exe
PuTTY:      E:\tools\ssh\winsshterm\WinSSHTerm\tools\putty.exe
Plink:      E:\tools\ssh\winsshterm\WinSSHTerm\tools\plink.exe
Pageant:    E:\tools\ssh\winsshterm\WinSSHTerm\tools\pageant.exe
WinSCP:     E:\tools\ssh\winsshterm\WinSSHTerm\tools\WinSCP\WinSCP.exe
VcXsrv:     E:\tools\ssh\winsshterm\WinSSHTerm\tools\VcXsrv\vcxsrv.exe

Hash Info (sha256)
==================
WinSSHTerm: 6879d37386bc90ad08238474c4cdbc3177c670de7e3125c77f033b7826ab2b43
PuTTY:      e53c379d95e95706c5a2c4d6cd609857368a3bf14f28d7e67f6e3f8dfce6d486
Plink:      b4862f8db04c475e5f96c302be83f42c0eda8411152ed84fa40c3170f69a813f
Pageant:    e9a85bc507f43e838b12650cecc121a0f5cb2baaa717c1c47d31c4bdbedaa03b
WinSCP:     a670932f6063603a31f9ba484ac5638bcc11618eb679cf8e69bd92178dcd4b0b
VcXsrv:     1e3df2848bab25b9912ec0b82a43dd188b1b7736455ac35781d2299f365e4308
