### ISSUE TITLE
Connection configuration check does not work with [IPv6] addresses

### ISSUE THREAD

**Issue by frankenstein91** [WinSSHTerm/WinSSHTerm#16]
I currently face the problem that I have to deactivate the verification of the configuration in the preference dialog.
Without this workaround, it is unfortunately impossible for me to establish a connection to IPv6 addresses written in square brackets.

Is my IPv6 notation erroneous or is this a missing implementation in the verification?

**Comment by WinSSHTerm** [comment]
Thanks for the bug report. This was fixed with version 2.33.5
