### ISSUE TITLE
Suggestion: Warn for PuTTY versions older than 0.81

### ISSUE THREAD

**Issue by dEajL3kA** [WinSSHTerm/WinSSHTerm#17]
PuTTY 0.81 fixes an important vulnerability regarding ECDSA:

> In PuTTY 0.68 through 0.80 before 0.81, biased ECDSA nonce generation allows an attacker to recover a user's NIST P-521 secret key via a quick attack in approximately 60 signatures.

Older versions up to and including version 0.80 should **not** be used. Any 521-bit ECDSA private key that was used with one of those older versions should be considered **compromised**. Therefore, WinSSHTerm should warn about these old PuTTY versions!

**See also:**
https://git.tartarus.org/?p=simon/putty.git;a=commit;h=c193fe9848f50a88a4089aac647fecc31ae96d27

**Comment by WinSSHTerm** [comment]
Thanks for your feedback, this was implemented in version 2.34.1
