### ISSUE TITLE
Central Config which can be captured in MSIX Package

### ISSUE THREAD

**Issue by Dragonsys** [WinSSHTerm/WinSSHTerm#18]
Is there a central config which can be used with MSIX to set the default location of putty.exe, when used with MSIX and App Layering?

I need a way to specify the location of or include putty.exe and the other clients along with the MSIX package, so when deployed within a Citrix environment the users do not need to provide the clients separately.

**Comment by WinSSHTerm** [comment]
Thanks for your feedback. If you install WinSSHTerm with the msi or msix package, the default location where WinSSHTerm looks for the client software is inside the user's documents directory:

```
PuTTY -> "$env:USERPROFILE\Documents\WinSSHTerm\tools\putty.exe"
Plink -> "$env:USERPROFILE\Documents\WinSSHTerm\tools\plink.exe"
Pageant -> "$env:USERPROFILE\Documents\WinSSHTerm\tools\pageant.exe"
WinSCP -> "$env:USERPROFILE\Documents\WinSSHTerm\tools\WinSCP\WinSCP.exe"
VcXsrv -> "$env:USERPROFILE\Documents\WinSSHTerm\tools\VcXsrv\vcxsrv.exe"
```

A way to set the location for the clients would be to create hard links (or symbolic links). With Powershell, you could set a hard link e.g. this way:

`New-Item -ItemType HardLink -Path "$env:USERPROFILE\Documents\WinSSHTerm\tools\putty.exe" -Target "PATH_TO_TARGET_PUTTY_EXE"`

(If the target is on another volume you'd have to use `SymbolicLink` as `ItemType`)

You could create these links before (or directly after) the msi/msix installation of WinSSHTerm to ensure all client software is set up on the first run.

Does this work for you?

**Comment by Dragonsys** [comment]
I'm not sure if this will work in my case due to the use of Folder Redirection, and the requirement of about 8000+ users.

So "$env:USERPROFILE\Documents" isn't valid I would have to use "\\$server\$share\folders\$env:username\Documents", also, only the user has permissions to this folder, so I would have to create the link in the user's context (so I can't pre-create them). I'm not sure if I can run a script when the package is loaded for the user, or if they only run when attached to the machine, I will have to check on this. But then, I also need to make sure the links are removed when the user logs off the system, due to the limit in the number of links allowed within a path.

**Comment by WinSSHTerm** [comment]
I'm thinking about supporting environment variables in WinSSHTerm. This way you could set the location for all users by creating a system-wide environment variable. Example (PowerShell):

`[Environment]::SetEnvironmentVariable("WINSSHTERM_PATH_PUTTY_BINARY", "C:\software\putty.exe", "Machine")`

Would this work for you?

**Comment by Dragonsys** [comment]
That would work, and I think it would be a great solution

**Comment by WinSSHTerm** [comment]
Support for environment variables was added in version 2.35.0 (see point 32 in the [FAQ section](https://winsshterm.blogspot.com/p/faq_10.html))
