### ISSUE TITLE
Script runner feature request

### ISSUE THREAD

**Issue by pablolite** [WinSSHTerm/WinSSHTerm#2]
Hello,

Your program is very useful. Well done!

I would like to report two feature request.
In "script runner" near by "connections" window:
1) CTRL+A does not select all hosts
2) Search by name is missing (like on the main screen)

Thanks,
Pawel

**Comment by WinSSHTerm** [comment]
Thanks, I'm working on a better way to filter connections. Will be probably available in the next release

**Comment by WinSSHTerm** [comment]
There will be a new feature "Connection Filter" in version 2.20.0. It will allow you to easily filter connections by the properties folder name, name, hostname, port, username and customid (if you are familiar with regular expressions). The filtered connections can be easily selected in Script Runner or Cluster Mode. It's quite powerful. I'm happy with the new feature:)

**Comment by WinSSHTerm** [comment]
https://github.com/WinSSHTerm/WinSSHTerm/releases/tag/2.20.0
