### ISSUE TITLE
WinSSHTerm changes PuTTY Session

### ISSUE THREAD

**Issue by LeonidPY** [WinSSHTerm/WinSSHTerm#21]
Hi. After update to 2.37.2 i noticed that hand changes in WinSSHTerm PuTTY session does not saved.
After restarting WinSSHTerm i see my changes rolled back to "default".
Couple of my changes:
![image](https://github.com/user-attachments/assets/323a8818-90ba-40d3-9637-f53f4a8f8ec6)
![image](https://github.com/user-attachments/assets/070652a9-caa0-44ec-97ef-ba99ec42de1c)
I can't find that changes in WinSSHTerm preferences, so i can't fix it.

**Comment by WinSSHTerm** [comment]
Thanks for your feedback. The bug should be fixed in this test version:
[WinSSHTerm-2.37.510.zip](https://github.com/user-attachments/files/16658254/WinSSHTerm-2.37.510.zip)
Does it work for you?

**Comment by WinSSHTerm** [comment]
This was fixed in release 2.37.3
