### ISSUE TITLE
Support for PuTTY CAC

### ISSUE THREAD

**Issue by frankenstein91** [WinSSHTerm/WinSSHTerm#3]
I don't know if it's hard to implement, but for professional use I would like to see [PuTTY-CAC](https://github.com/NoMoreFood/putty-cac) support. I think it is more secure than normal PuTTY.

**Comment by WinSSHTerm** [comment]
I don't think it is more secure than the official PuTTY

**Comment by frankenstein91** [comment]
@WinSSHTerm Please let me explain why I think this way. As far as I know, the normal PuTTY cannot use SmartCards. If I am wrong here, then my argument is invalid, but if so, please read on.

If I use a private key to log in with PuTTY or Pagent, then I have to store it on the computer or a removable storage device and secure it against theft accordingly. With a SmartCard, this is already built in. If the PIN is entered incorrectly too often, the private key is automatically destroyed. With a keyfile, unfortunately, offline attacks against the password are possible. 

@NoMoreFood how do you see this in comparison as a developer of the fork?

**Comment by WinSSHTerm** [comment]
Ok, that makes sense. I thought if authentication with SmartCards is more secure, then the PuTTY team would officially support it. However, I now found this wish (https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/smartcard-auth.html) where the they explain that it's difficult for them to implement it.

PuTTY-CAC seems to add new command line parameters. If authentication with SmartCards can be done by using these parameters, it should already be able to use it in WinSSHTerm. You would need to set the parameters in the field "Connection->Cmd-line Args". Does this work for you?

**Comment by frankenstein91** [comment]
Hi @WinSSHTerm 
Sorry for the late reply. I have checked the putty and pagent of the fork. It looks promising and worked out of the box. The only thing I would wish to have is a `-autoload` on the pagent to load all certificates of my Smartcard on startup.

**Comment by WinSSHTerm** [comment]
Hi @frankenstein91 
My idea is to add the option "Append custom command-line arguments" to File->Preferences->Pageant (same as with Copy Files). Then you could set the arguments as you need there. What do you think?

**Comment by frankenstein91** [comment]
So I think it would be a good idea, but could also be presented better. After all, it somehow belongs to the certificate list.
this makes me feel a little undecided about what would be better.

**Comment by WinSSHTerm** [comment]
@frankenstein91 There is now a test version 2.24.500
https://dl.winsshterm.net/WinSSHTerm-2.24.500.zip

I added the option "Append custom command-line arguments" to File->Preferences->Pageant. Does this work for you?

**Comment by WinSSHTerm** [comment]
The new option was released in version 2.24.0
