### ISSUE TITLE
Add an option to show parent folder names in the tab title

### ISSUE THREAD

**Issue by WinSSHTerm** [WinSSHTerm/WinSSHTerm#6]
See https://www.reddit.com/r/WinSSHTerm/comments/126fyne/pathname_as_default_title_for_the_tag/

**Comment by WinSSHTerm** [comment]
In this test version the new folder option "Tab Prefix" was added. The string will be added as prefix to the tab
[WinSSHTerm-2.26.501.zip](https://github.com/WinSSHTerm/WinSSHTerm/files/11239870/WinSSHTerm-2.26.501.zip)
 title of the connection.

**Comment by phate89** [comment]
I tried it today and it seems to works very well! thanks!

**Comment by WinSSHTerm** [comment]
> I tried it today and it seems to works very well! thanks!

Thanks for testing

**Comment by WinSSHTerm** [comment]
Implemented in version 2.26.0
