### ISSUE TITLE
Connection Groups

### ISSUE THREAD

**Issue by iainjohnstone1972** [WinSSHTerm/WinSSHTerm#7]
Can you please add an option to stop closing active sessions when selecting a connection group to open. We should be able to add them to the existing connections.

**Comment by WinSSHTerm** [comment]
Thanks for your feedback. I made a test version. You'll notice a new option in the Edit groups dialog. Does this work for you?
[WinSSHTerm-2.26.500.zip](https://github.com/WinSSHTerm/WinSSHTerm/files/11238868/WinSSHTerm-2.26.500.zip)

**Comment by iainjohnstone1972** [comment]
Thanks - I can see this on my Personal Laptop however my work one I am not able to run the program due to a security defence. I will see if I can get this resolved and report back.

**Comment by iainjohnstone1972** [comment]
Perfect I have this working now. Thankyou so much for adding this.
